# Generated by Django 4.2.6 on 2023-10-07 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SupportTicket', '0001_initial'),
        ('Feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='SupportTicket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_ticket', to='SupportTicket.supportticket'),
        ),
    ]
