# Generated by Django 4.2.6 on 2023-10-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Beneficiary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='barangay',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
