# Generated by Django 4.2.6 on 2023-10-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Beneficiary', '0002_address_barangay_address_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='UserType',
            field=models.CharField(choices=[('donor', 'Donor'), ('beneficiary', 'Beneficiary'), ('admin', 'Admin')], default='beneficiary', max_length=12),
        ),
    ]
