# Generated by Django 4.2.6 on 2023-10-05 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amount_Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('CurrencyID', models.BigAutoField(primary_key=True, serialize=False)),
                ('CurrencyType', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='DIK',
            fields=[
                ('DikID', models.BigAutoField(primary_key=True, serialize=False)),
                ('DikType', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('UserID', models.BigAutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('EmailAddress', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=20)),
                ('UserType', models.CharField(choices=[('donor', 'Donor'), ('beneficiary', 'Beneficiary'), ('admin', 'Admin')], max_length=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Goods_Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GoodsDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('Expiry', models.DateField()),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CashDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.FloatField()),
                ('Date', models.DateField()),
                ('donorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Donor.donor')),
            ],
        ),
    ]
