# Generated by Django 4.2.6 on 2023-10-05 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashdetails',
            name='donorID',
        ),
    ]
