# Generated by Django 4.2.6 on 2023-10-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0002_remove_cashdetails_donorid'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='DonationType',
            field=models.CharField(choices=[('cash', 'Cash'), ('materials', 'Materials')], default='cash', max_length=10),
        ),
    ]
