# Generated by Django 4.2.6 on 2023-10-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0003_donor_donationtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='UserType',
            field=models.CharField(choices=[('donor', 'Donor'), ('beneficiary', 'Beneficiary'), ('admin', 'Admin')], default='donor', max_length=12),
        ),
    ]
