# Generated by Django 4.2.6 on 2023-10-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminStaff',
            fields=[
                ('UserID', models.BigAutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('EmailAddress', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=20)),
                ('UserType', models.CharField(choices=[('donor', 'Donor'), ('beneficiary', 'Beneficiary'), ('admin', 'Admin')], max_length=12)),
                ('Username', models.CharField(default='admin', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
