# Generated by Django 4.2.6 on 2023-10-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminStaff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminstaff',
            name='UserType',
            field=models.CharField(choices=[('donor', 'Donor'), ('beneficiary', 'Beneficiary'), ('admin', 'Admin')], default='Admin', max_length=12),
        ),
    ]
